### ISSUE TITLE
Wrong image tag for version 0.1.1

### ISSUE THREAD

**Issue by TannerGabriel** [keptn-sandbox/job-executor-service#13]
The new version `0.0.1` of the `job-executor-service` is not tagged as `keptnsandbox/job-executor-service:0.1.1` as described in the README and used in the Kubernetes and Helm files but is tagged as `keptnsandbox/job-executor-service:0-1-1` instead. This seems to be the case because the release branch is named `release-0-1-1` instead of `release-0.1.1`, and the branch name is used in the [Github Action](https://github.com/keptn-sandbox/job-executor-service/blob/main/.github/workflows/CI.yml#L76), which builds the Docker image.

It would be great to change the tag of this release so that the given installation scripts work correctly.

**Comment by yeahservice** [comment]
I pushed the images with the correct tag `0.1.1`
