### ISSUE TITLE
Make it possible to add additional data to finished events

### ISSUE THREAD

**Issue by yeahservice** [keptn-sandbox/job-executor-service#19]
Certain keptn services expect specific data blocks in the started events to do their work correctly. For example the test.finished event has a test block with data needed for the evaluation step (https://github.com/keptn/spec/blob/master/cloudevents.md#test-finished)

```json
    "test": {
      "start": "2019-10-20T07:57:27.152330783Z",
      "end": "2019-10-20T08:57:27.152330783Z",
      "gitCommit": "ca82a6dff817gc66f44342007202690a93763949"
    }
```

Since the most appealing use-case for the job-executor-service seems to be tests, we should support it in some way.

I see two possible solutions:
1. Ability to define custom json data for a task that gets added to the .finished event.
* E.g. write a valid json block into some specific file, the job-executor-service takes the json data block from this file and adds it to the .finished event.
* Disadvantage would be that all users would have to write custom code to fulfill the requirements for the standard events. If a keptn update adds an additional property each configuration needs to be adjusted as well.

2. Out of the box support for official event types (https://github.com/keptn/spec/blob/master/cloudevents.md)
* The service could support the standard events without any need to configure anything
* E.g. for an incoming test event take the start time, start the job, take the end time and add both properties in a test block to the .finished event
* Advantage would be that the user doesn't need to care about any additional configurations. If a keptn update adds additional properties we can just add them in our release that supports that specific keptn version.
* Still can support custom json blocks if need arises

I am in strong favor of option 2. We can start out with support for test events and add other events over time.

**Comment by yeahservice** [comment]
As discussed with @didiladi, we will go with option 2 and just support `test` events in the first implementation.

**Comment by jetzlstorfer** [comment]
Is there any rough timeline for when this will be implemented?

**Comment by yeahservice** [comment]
@jetzlstorfer is there any specific use case you have in mind for this feature? Like support for only specific event types or any custom data that could be added to an event?

We did not have it on our radar in the near future but it feels like a missing core feature so that jobs can be used for any task in a shipyard sequence.

**Comment by didiladi** [comment]
@jetzlstorfer I'm planning to work on that this week. Hopefully by the end of the week there will be something to show/review.

**Comment by TannerGabriel** [comment]
@yeahservice Yes, I have a specific use case with the JMeter service where I received the following error from the evaluation (after the tests were successful): `evaluation.triggered event does not contain evaluation timeframe`.

This seems to be the case since the `TestFinishedEvent` does not contain a start and end time, but #64 seems to fix the problem for me.
