### ISSUE TITLE
Allow specifying working dir in job config impl

### ISSUE THREAD

**Issue by patrickpichler** [keptn-sandbox/job-executor-service#37]
Since all files mounted in the container will be located under `/keptn` and 
some tools do not take an CWD as argument, it is often required to change 
the entrypoint of containers to `sh -c` and put some `cd ... && ...` into the 
job definitions.

According to the [kubernetes api docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#container-v1-core)
there is a `workingDir` property available. There should be  a new config property
in the task object, which sets this property when spawning the k8s job.

**Comment by yeahservice** [comment]
good to go
