### ISSUE TITLE
Job timeout should be configurable

### ISSUE THREAD

**Issue by donovanmuller** [keptn-sandbox/job-executor-service#40]
Currently both `maxPollCount` and `pollIntervalInSeconds` are hard coded and result in a 5 minute timeout. https://github.com/keptn-sandbox/job-executor-service/blob/166ca51829e3eefebbb6618dd199093fa27c64f4/pkg/k8sutils/job.go#L182-L183 

Upon which the Job reports a failure message.

These values should be configurable, as I have some Jobs that exceed 5 minutes.

**Comment by didiladi** [comment]
This makes sense! Good idea!

Another (possibly more user-friendly) option would be to configure the `maxPollDuration` - the maximal time a job is allowed to run. Then we could hardcode the `pollIntervalInSeconds` and calculate the `maxPollCount`.

Question is: Is there a need to configure that per task, or globally for the service?

**Comment by donovanmuller** [comment]
@didiladi I would say per task probably makes more sense (default timeout should be ok for most Jobs and then explicitly adjust for specific tasks that you know can take a while to complete) but I don't have any strong feelings either way.
