### ISSUE TITLE
Problem with `valueFrom: event` formatting

### ISSUE THREAD

**Issue by TannerGabriel** [keptn-sandbox/job-executor-service#59]
For some specific services you may need to pass the whole Keptn event into the container using an environment variable which can currently be done using the following syntax:

```
env:
          - name: EVENT
            value: "$"
            valueFrom: event
```

When reading through [the code](https://github.com/keptn-sandbox/job-executor-service/blob/770dc0ffb05d6cf5f32c27cda233d2556e1c6a9a/pkg/eventhandler/eventhandlers.go#L105) you get the impression that the event data is stored as JSON which would be easy to work with once read through the environment variable but it seems that the event is formatted as an [map[string]interface](https://github.com/keptn-sandbox/job-executor-service/blob/c45ce5924e559f26b422e3c8a90c37f8587ca723/pkg/eventhandler/eventhandlers.go#L70) instead which leaves you with the following value when using the environment variable:

```bash
map[data:map[configurationChange:map[values:map[image:docker.io/keptnexamples/carts:0.12.3]] deployment:map[deploymentNames:[direct] deploymentURIsLocal:[http://carts.sockshop-dev:80] deploymentURIsPublic:[http://carts.sockshop-dev.IP_ADDRESS.nip.io:80] deploymentstrategy:direct gitCommit:b02c3afdcd539dbe33c461e75d4d5365acff914b] message: project:sockshop result:pass service:carts stage:dev status:succeeded test:map[teststrategy:functional]] id:daa042d5-31b8-443e-826b-c26505da84ff shkeptncontext:fc3f12ac-cda8-483c-944a-985bfef3b102 source:shipyard-controller time:2021-08-05 17:29:51.323554006 +0000 UTC]
```

This format has proven quite hard to cast (extract the keys and values). Is there a way to get the same data in another format like JSON or YAML? Or is there a preferred way of casting the result to a Keptn event?

**Comment by didiladi** [comment]
Hey @TannerGabriel, 

you are right, the resulting string is difficult to work with. So far we did not have the use case to receive the full keptn event and to pass it along as env var to the job. What we usually do is to extract a string from the keptn event and pass it along to the job.

Feel free to open a PR, I believe your use case is a valid one :). You'd need to touch the following code: https://github.com/keptn-sandbox/job-executor-service/blob/770dc0ffb05d6cf5f32c27cda233d2556e1c6a9a/pkg/k8sutils/job.go#L271

I see two options of how this could be implemented:

**Option 1:**
Make the output format configurable. Something like:

```
env:
          - name: EVENT
            value: "$"
            valueFrom: event
            as: json|string (string is the default if you omit it)
```

**Option 2:**

Check the type first. If the extracted content is of type map -> format it as json. If it is a string -> leave it as is. This might be on the one hand more user-friendly, but on the other hand harder to understand.

@TannerGabriel, @yeahservice what do you think of the two options above?

**Comment by TannerGabriel** [comment]
I personally think that both methods would be fine. The first one gives you more configuration options as you could also add other formats like YAML in the future, but the second one works fine as well.

**Comment by yeahservice** [comment]
I would like to keep the configuration more one the user-friendly side, since it can get quite verbose already. I like option 1 but would keep the whole ```as: json|string``` as default so we would kinda get the best of both options.

**Comment by TannerGabriel** [comment]
That sounds reasonable. I could probably implement the functionality and open a PR today if that is ok with you @yeahservice.

**Comment by yeahservice** [comment]
That would be awesome :+1:
