### ISSUE TITLE
INIT_CONTAINER_IMAGE default value should include valid tag

### ISSUE THREAD

**Issue by donovanmuller** [keptn-sandbox/job-executor-service#9]
The `deploy/service.yaml` manifest contains a default [value](https://github.com/keptn-sandbox/job-executor-service/blob/6583d45c8dc76c3ed8c7e27b2e7f058f84291d6f/deploy/service.yaml#L31) for the `INIT_CONTAINER_IMAGE` of `keptnsandbox/job-executor-service-initcontainer`.

However, there is [not currently](https://hub.docker.com/r/keptnsandbox/job-executor-service-initcontainer/tags?page=1&ordering=last_updated&name=latest) an image pushed with a `latest` tag, so running the Job fails.

The `INIT_CONTAINER_IMAGE` value should probably include the [same tag](https://github.com/keptn-sandbox/job-executor-service/blob/6583d45c8dc76c3ed8c7e27b2e7f058f84291d6f/deploy/service.yaml#L20) as the `job-executor-service` service.

**Comment by yeahservice** [comment]
This should already be fixed with https://github.com/keptn-sandbox/job-executor-service/pull/5

**Comment by donovanmuller** [comment]
@yeahservice the PR only changed the value in the Helm ConfigMap (`helm/templates/configmap.yaml`) though, not the `deploy/service.yaml` manifest?

**Comment by yeahservice** [comment]
Ah, my bad, I overlooked that one.
